
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  3 2023 19:40:12 IST (May  3 2023 14:10:12 UTC)

// Verification Directory fv/Sbox_4bit 

module Sbox_4bit(OPT, INP);
  input [3:0] INP;
  output [3:0] OPT;
  wire [3:0] INP;
  wire [3:0] OPT;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12;
  AO21M1SA g188(.A1 (n_9), .A2 (INP[3]), .B (n_10), .Z (OPT[2]));
  OAI221M1S g189(.A1 (INP[1]), .A2 (n_7), .B1 (n_8), .B2 (n_6), .C
       (n_3), .Z (OPT[0]));
  MOAI22M1SA g191(.A1 (n_12), .A2 (n_11), .B1 (n_12), .B2 (n_11), .Z
       (OPT[3]));
  OAI33M1S g190(.A1 (INP[1]), .A2 (INP[3]), .A3 (n_9), .B1 (n_8), .B2
       (n_5), .B3 (n_2), .Z (n_10));
  ND2M1S g192(.A (n_6), .B (INP[2]), .Z (n_7));
  OAI21M1S g196(.A1 (INP[3]), .A2 (n_5), .B (n_6), .Z (n_12));
  AO21M1SA g193(.A1 (n_0), .A2 (INP[2]), .B (n_1), .Z (OPT[1]));
  OAI21M1S g195(.A1 (INP[0]), .A2 (INP[1]), .B (n_2), .Z (n_3));
  AO21M1SA g194(.A1 (INP[2]), .A2 (INP[0]), .B (n_1), .Z (n_9));
  ND2M1S g200(.A (n_5), .B (INP[3]), .Z (n_6));
  NR2M1S g198(.A (INP[2]), .B (INP[3]), .Z (n_2));
  ND2M1S g199(.A (INP[2]), .B (INP[1]), .Z (n_11));
  NR2M1S g197(.A (INP[0]), .B (INP[2]), .Z (n_1));
  CKINVM1S g202(.A (INP[1]), .Z (n_8));
  CKINVM1S g203(.A (INP[3]), .Z (n_0));
  CKINVM1S g201(.A (INP[0]), .Z (n_5));
endmodule

